### ISSUE TITLE
DPR Reader 

### ISSUE THREAD

**Issue by lucifermorningstar1305** [xsc1234/Search-in-the-Chain#1]
Hi,

First, thanks a lot for creating and open-sourcing such amazing work. I was going through your codebase, and in the `Server/retrieval/reader.py` file, I found this line for the DPR reader:

```python
tokenizer = DPRReaderTokenizer.from_pretrained("/dpr_reader_multi")
model = DPRReaderTokenizer.from_pretrained("/dpr_reader_multi")
```

The DPR model referenced over here, is it some locally trained checkpoint? I couldn't find it on HuggingFace Models Hub.

I appreciate any help you can provide.

**Comment by xsc1234** [comment]
You can find it here: https://huggingface.co/facebook/dpr-reader-multiset-base
