### ISSUE TITLE
可以提供一下wiki数据集的链接嘛～

### ISSUE THREAD

**Issue by Gy915** [xsc1234/Search-in-the-Chain#2]
您好，读完后paper感觉是很棒的工作！
我们在复现的时候，发现”/hotpotqa/enwiki-20171001-pages-meta-current-withlinks-abstracts.tsv“数据集不存在，我们尝试从hotpotqa官网上下载，发现这个文件对链接已经损坏了，所以想请问一下是否能提供相关的下载链接或者相关的数据集网盘供我们复现？

**Comment by xsc1234** [comment]
You can download the data from here: 
链接：https://pan.baidu.com/s/1wgBbja86LRua61t9ezfGNw 
提取码：icun 
--来自百度网盘超级会员V5的分享
