### ISSUE TITLE
Loading ColBERT weights

### ISSUE THREAD

**Issue by lucifermorningstar1305** [xsc1234/Search-in-the-Chain#3]
Hi, 

So when I was trying to run the `index.py` file under `ColBERT/` I got this error:

```
OSError: Unable to load weights from pytorch checkpoint file for './colbertv2.0/pytorch_model.bin' at './colbertv2.0/pytorch_model.bin'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
```

I have downloaded the ColBERT weights from the ColBERT repository on GitHub.

**Comment by xsc1234** [comment]
Can you provide more detailed in loading code and file format of the model? I am currently unable to judge the specific problem based on the information you provide

**Comment by lucifermorningstar1305** [comment]
Hi,

I'm sorry for not getting back to you sooner. It was a problem from my end where my downloaded weights were not correctly downloaded, and I fixed it by following the latest instructions from the Colbert repository.
