### ISSUE TITLE
need requirement.txt

### ISSUE THREAD

**Issue by suiyize** [xsc1234/Search-in-the-Chain#4]
Hello, we think this is a great job! Can you provide the requirement.txt file so that we can better reproduce your code

**Comment by liuxiaocs7** [comment]
+1, @xsc1234

**Comment by xsc1234** [comment]
Very sorry for the late reply：
To reproduce the interaction between LLM and IR:

joblib==1.0.1
matplotlib==3.5.3
nltk==3.6.2
numpy==1.21.6
openai==0.27.2
regex==2021.4.4
tqdm==4.64.0

To reproduce the retriever (Colbert), we recommend you refer to https://github.com/stanford-futuredata/ColBERT
