### ISSUE TITLE
Questions about "Cover-EM"

### ISSUE THREAD

**Issue by dlgusals1414** [xsc1234/Search-in-the-Chain#6]
Hello,

Firstly, I want to express my sincere gratitude for sharing your exceptional research and code. The innovative idea, along with the impressive results and the clarity of the paper, truly stand out.

After a thorough review of your code in the context of your paper, I encountered an area I couldn't quite grasp regarding the evaluation of your metric, Cover-em. My queries are primarily focused on understanding the evaluation process in two specific aspects:

How do you determine if the predicted answer (predict_answer) accurately contains the correct answer? 
For instance, using a pseudo code approach: 

1. if answer in predict_answer: score += 1
2. if answer in final_answer: score += 1

Thank you once again for making your remarkable paper and code available, and congratulations on your acceptance to [WWW]

**Comment by xsc1234** [comment]
Thanks for your attention！
The way we determine how the predicted answer accurately contains the correct answer is:
1. Get the multi-round response (message_keys_list) from LLM
2. Traverse LLM’s responses from back to front.
3. Determine whether 'Final Content' in the response
4. Extract the answer behind 'Final Content'.
5. Normalize answers to determine whether the correct answer appears in the extracted answer.
You can get a quick start from SearChain@LLamaIndex [here](https://docs.llamaindex.ai/en/stable/api_reference/packs/searchain/#llama_index.packs.searchain.SearChainPack)

**Comment by dlgusals1414** [comment]
I understand exactly!
Thanks for the detailed answer.
